import animate from 'tailwindcss-animate';
import rtl from 'tailwindcss-rtl';

export default {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '1.25rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '2.5rem',
        '2xl': '3rem',
      },
    },
    extend: {
      fontFamily: {
        arabic: [
          'Tajawal',
          'Cairo',
          'Noto Sans Arabic',
          'sans-serif',
        ],
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',

        // Design Tokens - Background (Light + Dark)
        'bg': 'var(--bg)',
        'bg-base': 'var(--color-bg-base)',
        'bg-subtle': 'var(--color-bg-subtle)',
        'bg-muted': 'var(--color-bg-muted)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'bg-overlay': 'var(--color-bg-overlay)',

        // Design Tokens - Text (Light + Dark)
        'text': 'var(--text)',
        'text-2': 'var(--text-2)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-inverse': 'var(--color-text-inverse)',

        // Design Tokens - Border (Light + Dark)
        'border': 'var(--border)',
        'border-base': 'var(--color-border-base)',
        'border-strong': 'var(--color-border-strong)',
        'border-focus': 'var(--color-border-focus)',

        // Semantic Aliases for Light Theme
        'surface': 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
        'border-ui': 'var(--border)',
        'muted': 'var(--muted)',
        'primary': {
          DEFAULT: 'var(--primary)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
        },
        'primary-hover': 'var(--primary-hover)',

        brand: {
          50: '#eef7ff',
          100: '#d6ebff',
          200: '#add6ff',
          300: '#7bbcff',
          400: '#4a9dff',
          500: '#1f7fff',
          600: '#1765d6',
          700: '#124fac',
          800: '#0d3b82',
          900: '#0a2c63',
        },
        success: {
          DEFAULT: 'var(--success)',
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          950: '#052011',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          950: '#331a00',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          50: 'var(--color-danger-50)',
          100: 'var(--color-danger-100)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
          950: '#330505',
        },
        error: {
          DEFAULT: 'var(--danger)',
          50: 'var(--color-danger-50)',
          100: 'var(--color-danger-100)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
          950: '#330505',
        },
        info: {
          DEFAULT: 'var(--info)',
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          950: '#052030',
        },
        'row-hover': 'var(--row-hover)',
        'row-selected': 'var(--row-selected)',
        neutral: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
        'card': 'var(--radius-card)',
        'btn': 'var(--radius-btn)',
      },
      boxShadow: {
        soft: '0 1px 2px 0 rgb(0 0 0 / 0.05), 0 8px 24px -20px rgb(0 0 0 / 0.25)',
        card: 'var(--shadow-card)',
      },
      screens: {
        'xs': '360px',
        'sm': '414px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
        '3xl': '1920px',
      },
    },
  },
  plugins: [rtl, animate],
};
