jobs:
name: Phase Reports
on: [push]
jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm reports:aggregate
      - uses: actions/upload-artifact@v4
        with:
          name: phase-reports
          path: reports/summary.json
